name = "rssworker"
main = "src/worker.js"
compatibility_date = "2026-07-25"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "rss.zjkl.qzz.io", custom_domain = true }
]

[observability]
enabled = true

[[kv_namespaces]]
binding = "data"
id = "35eb361144044abd8c2f88b9baae4a17"
